import { NextRequest, NextResponse } from 'next/server';
import {
  createGuideCamping, createGuidePlace, createGuideBeach,
  createGuideAttraction, createGuideRestaurant, createGuideBlogPost,
  getGuideCampings, getGuidePlaces, getGuideBeaches,
  getGuideAttractions, getGuideRestaurants, getGuideBlogPosts,
} from '@/lib/db';

function verifySetupKey(request: NextRequest): boolean {
  const key = process.env.SETUP_SECRET_KEY || process.env.ADMIN_SECRET;
  if (!key) return false;
  const provided = request.headers.get('x-setup-key') || new URL(request.url).searchParams.get('key');
  if (!provided) return false;
  return key === provided;
}

const campings = [
  { name: 'Camping Cala Gogo', slug: 'camping-cala-gogo', town: 'Calonge', region: 'Costa Brava', stars: 4, price_range: '€€€', description: 'Luxe camping direct aan het strand van Calonge, met groot aquapark en animatie. Ideaal voor families met kinderen.', amenities: ['Zwembad','Restaurant','Supermarkt','WiFi','Kinderclub','Aquapark'], highlights: ['Direct aan strand','Aquapark','Avondentertainment'], website: 'https://www.calagogo.es', lat: 41.8434, lng: 3.0852, is_featured: true },
  { name: 'Camping Cypsela', slug: 'camping-cypsela', town: 'Pals', region: 'Costa Brava', stars: 5, price_range: '€€€', description: 'Premium 5-sterren resort in Pals met spectaculair zwembadcomplex, wellness-spa en directe toegang tot het strand.', amenities: ['Spa','Zwembaden','Tennis','Restaurant','Supermarkt','WiFi','Animatie'], highlights: ['5-sterren luxe','Spa & Wellness','Groot zwembadcomplex'], website: 'https://www.cypsela.com', lat: 41.9756, lng: 3.1843, is_featured: true },
  { name: 'Camping Castell Montgri', slug: 'camping-castell-montgri', town: "L'Estartit", region: 'Costa Brava', stars: 4, price_range: '€€', description: "Goed gelegen camping nabij de Medes-eilanden met uitstekende duikmogelijkheden en uitgebreide faciliteiten.", amenities: ['Zwembad','Restaurant','Duikschool','WiFi','Speeltuin'], highlights: ['Nabij Medes-eilanden','Duikmogelijkheden','Rustige ligging'], website: 'https://www.castellmontgri.com', lat: 42.0515, lng: 3.1877, is_featured: true },
  { name: 'Camping Treumal', slug: 'camping-treumal', town: 'Calonge', region: 'Costa Brava', stars: 3, price_range: '€€', description: 'Charmante camping verscholen in een pijnbomenbos, op loopafstand van prachtige stranden.', amenities: ['Zwembad','Bar','Speeltuin','WiFi'], highlights: ['Schaduwrijke plekken','Rustige sfeer','Loopafstand strand'], lat: 41.8505, lng: 3.0801 },
  { name: 'Camping Valldaro', slug: 'camping-valldaro', town: 'Platja d\'Aro', region: 'Costa Brava', stars: 4, price_range: '€€€', description: 'Moderne camping in het centrum van Platja d\'Aro met groot aquapark en directe strandtoegang.', amenities: ['Aquapark','Restaurant','Supermarkt','Wellness','WiFi','Animatie'], highlights: ['Centraal gelegen','Aquapark','Veel winkels dichtbij'], website: 'https://www.campingvalldaro.com', lat: 41.8141, lng: 3.0625 },
  { name: 'Camping El Delfin Verde', slug: 'camping-el-delfin-verde', town: 'Torroella de Montgrí', region: 'Costa Brava', stars: 4, price_range: '€€', description: 'Enorme camping direct aan het lange zandstrand van Pals, populair bij Nederlandse gezinnen.', amenities: ['Zwembad','Restaurant','Supermarkt','Tennisbanen','WiFi','Kinderanimatie'], highlights: ['Grootste camping Costa Brava','Direct aan strand','Nederlandse animatie'], website: 'https://www.eldelfinverde.com', lat: 42.0000, lng: 3.1990, is_featured: true },
  { name: 'Camping Begur', slug: 'camping-begur', town: 'Begur', region: 'Costa Brava', stars: 3, price_range: '€€', description: 'Rustige familiecamping in het groene binnenland van Begur, op korte rijafstand van meerdere cala\'s.', amenities: ['Zwembad','Snackbar','Speeltuin','WiFi'], highlights: ['Rustig gelegen','Nabij mooiste cala\'s','Schaduwrijk'], lat: 41.9555, lng: 3.2100 },
  { name: 'Camping Mas Sant Josep', slug: 'camping-mas-sant-josep', town: 'Santa Cristina d\'Aro', region: 'Costa Brava', stars: 4, price_range: '€€', description: 'Sfeervolle camping met karakter tussen kurkeiken, uitstekende gastronomie in eigen restaurant.', amenities: ['Zwembad','Restaurant','WiFi','Fietsverhuur','Massage'], highlights: ['Gastronomische restaurant','Prachtige natuur','Fietsen'], website: 'https://www.campingmassantjosep.com', lat: 41.8267, lng: 2.9748 },
  { name: 'Camping Inter Pals', slug: 'camping-inter-pals', town: 'Pals', region: 'Costa Brava', stars: 3, price_range: '€€', description: 'Populaire camping bij Nederlanders en Belgen met gezellige sfeer en goede faciliteiten in Pals.', amenities: ['Zwembad','Restaurant','Bar','WiFi','Animatie','Supermarkt'], highlights: ['Gezellige sfeer','Populair bij NL/BE','Nabij strand Pals'], website: 'https://www.interpals.com', lat: 41.9700, lng: 3.1612 },
  { name: 'Camping Kim\'s', slug: 'camping-kims', town: 'Llafranc', region: 'Costa Brava', stars: 3, price_range: '€€€', description: 'Kleine boutique camping met panoramisch uitzicht over zee, vlakbij het charmante dorpje Llafranc.', amenities: ['Zwembad','Bar','WiFi','Panoramisch terras'], highlights: ['Zeezicht','Intiem & rustig','Loopafstand Llafranc'], lat: 41.8906, lng: 3.1939 },
  { name: 'Camping La Ballena Alegre', slug: 'camping-la-ballena-alegre', town: 'Sant Pere Pescador', region: 'Costa Brava', stars: 4, price_range: '€€', description: 'Uitgestrekte beachfront camping perfect voor windsurfen en kitesurfen aan de Golf van Roses.', amenities: ['Zwembad','Restaurant','Surfschool','WiFi','Supermarkt','Speeltuin'], highlights: ['Direct aan strand','Watersport paradijs','Groot terrein'], website: 'https://www.ballena-alegre.com', lat: 42.1788, lng: 3.1055, is_featured: true },
  { name: 'Camping Nautic Almata', slug: 'camping-nautic-almata', town: 'Castelló d\'Empúries', region: 'Costa Brava', stars: 4, price_range: '€€', description: 'Unieke camping in het natuurpark Aiguamolls de l\'Empordà, perfect voor natuurliefhebbers en vogelaars.', amenities: ['Zwembad','Restaurant','Kajak','WiFi','Natuurexcursies'], highlights: ['In natuurpark','Vogelobservatie','Kajakken'], website: 'https://www.almata.com', lat: 42.2333, lng: 3.1167 },
  { name: 'Camping Illa Mateua', slug: 'camping-illa-mateua', town: "L'Escala", region: 'Costa Brava', stars: 3, price_range: '€', description: "Betaalbare camping in L'Escala, bekend om de ansjovis, met gezellige sfeer en goede ligging.", amenities: ['Zwembad','Bar','WiFi','Speeltuin'], highlights: ['Betaalbaar','Loopafstand centrum','Authentiek Spaans'], lat: 42.1208, lng: 3.1355 },
  { name: 'Camping Sandaya Mas de l\'Ombrie', slug: 'camping-sandaya-mas-ombrie', town: 'Calonge', region: 'Costa Brava', stars: 5, price_range: '€€€', description: 'Luxueus glamping resort met premium stacaravans, uitgebreid wellness center en sterrenchef.', amenities: ['Wellness','Gastronomisch restaurant','Zwembaden','WiFi','Yoga','Kids club'], highlights: ['Glamping luxe','Wellness spa','Gastronomie'], lat: 41.8550, lng: 3.0700 },
  { name: 'Camping Ridaura', slug: 'camping-ridaura', town: 'Platja d\'Aro', region: 'Costa Brava', stars: 3, price_range: '€', description: 'Gezellige familiecamping op loopafstand van het strand en centrum van Platja d\'Aro.', amenities: ['Zwembad','Bar','WiFi','Speeltuin','Wasmachines'], highlights: ['Goede prijs-kwaliteit','Centraal gelegen','Familievriendelijk'], lat: 41.8170, lng: 3.0540 },
  { name: 'Camping Tamariu', slug: 'camping-tamariu', town: 'Tamariu', region: 'Costa Brava', stars: 2, price_range: '€€', description: 'Sfeervolle kleine camping op heuvel boven het idyllische vissersdorpje Tamariu met prachtig uitzicht.', amenities: ['Zwembad','Bar','WiFi'], highlights: ['Uitzicht over zee','Charmant dorp','Rustig'], lat: 41.9186, lng: 3.2192 },
  { name: 'Camping Riembau', slug: 'camping-riembau', town: 'Platja d\'Aro', region: 'Costa Brava', stars: 3, price_range: '€€', description: 'Goed onderhouden camping met schaduwrijke plekken onder pijnbomen, 10 minuten lopen van het strand.', amenities: ['Zwembad','Restaurant','WiFi','Tennisbaan','Tafeltennis'], highlights: ['Schaduwrijke plekken','Goed onderhouden','Rustige ligging'], lat: 41.8200, lng: 3.0480 },
  { name: 'Camping Neus', slug: 'camping-neus', town: "L'Estartit", region: 'Costa Brava', stars: 3, price_range: '€', description: "Kleinschalige camping vlakbij het centrum van L'Estartit en de haven. Perfect als uitvalsbasis voor de Medes-eilanden.", amenities: ['Zwembad','Bar','WiFi','Winkel'], highlights: ['Betaalbaar','Dichtbij haven','Goede uitvalsbasis'], lat: 42.0490, lng: 3.1850 },
  { name: 'Camping Santa Cristina', slug: 'camping-santa-cristina', town: 'Lloret de Mar', region: 'Costa Brava', stars: 3, price_range: '€€', description: 'Direct bij het paradijselijke strand Santa Cristina, een van de mooiste stranden van de Costa Brava.', amenities: ['Zwembad','Restaurant','WiFi','Duikcentrum','Snorkeluitrusting'], highlights: ['Prachtig strand','Snorkelmogelijkheden','Rustig stuk Lloret'], lat: 41.7050, lng: 2.8170 },
  { name: 'Camping Cala Llevadó', slug: 'camping-cala-llevado', town: 'Tossa de Mar', region: 'Costa Brava', stars: 3, price_range: '€€', description: "Ecologische terrassencamping met eigen cala's en spectaculair uitzicht op de Middellandse Zee.", amenities: ['Zwembad','Restaurant','Duiken','WiFi','Yoga'], highlights: ['Eigen stranden','Eco-camping','Spectaculair uitzicht'], website: 'https://www.calallevado.com', lat: 41.7322, lng: 2.8944, is_featured: true },
];

const places = [
  { name: 'Tossa de Mar', slug: 'tossa-de-mar', town: 'Tossa de Mar', region: 'Costa Brava', population: '5900', description: 'Pittoresk kuststadje met een spectaculaire middeleeuwse ommuurde stad (Vila Vella) die direct over zee uitkijkt. Het werd door Marc Chagall "het blauwe paradijs" genoemd.', highlights: ['Vila Vella','Strand Gran','Vuurtoren Far de Tossa','Museu Municipal'], is_featured: true, lat: 41.7185, lng: 2.9316 },
  { name: 'Begur', slug: 'begur', town: 'Begur', region: 'Costa Brava', population: '4100', description: 'Charmant middeleeuws bergdorp met Indianos-architectuur en toegang tot de mooiste cala\'s van de Costa Brava.', highlights: ['Kasteel van Begur','Sa Riera','Aiguablava','Sa Tuna','Indianos-huizen'], is_featured: true, lat: 41.9544, lng: 3.2073 },
  { name: 'Cadaqués', slug: 'cadaques', town: 'Cadaqués', region: 'Costa Brava', population: '2800', description: 'Het witte vissersdorp dat Salvador Dalí inspireerde, bereikbaar via kronkelende bergwegen. Artistieke sfeer en prachtige natuurlijke haven.', highlights: ['Casa-Museu Dalí Portlligat','Kerk Santa Maria','Cap de Creus','Kunstgalerijen'], is_featured: true, lat: 42.2887, lng: 3.2766 },
  { name: 'Pals', slug: 'pals', town: 'Pals', region: 'Costa Brava', population: '2500', description: 'Middeleeuws dorp op een heuvel met gotische architectuur, een ronde toren en spectaculair uitzicht over de rijstvelden richting zee.', highlights: ['Torre de les Hores','Gotische kern','Rijstvelden','Strand van Pals'], is_featured: true, lat: 41.9717, lng: 3.1489 },
  { name: 'Peratallada', slug: 'peratallada', town: 'Peratallada', region: 'Costa Brava', population: '400', description: 'Een van de best bewaarde middeleeuwse dorpen van Catalonië, letterlijk "gehakte steen" met in rots uitgehakte grachten.', highlights: ['Castillo de Peratallada','Plaça de les Voltes','Middeleeuwse straten','Gastronomische restaurants'], is_featured: true, lat: 41.9875, lng: 3.0955 },
  { name: 'Calella de Palafrugell', slug: 'calella-de-palafrugell', town: 'Calella de Palafrugell', region: 'Costa Brava', population: '700', description: 'Idyllisch vissersdorpje met witte huisjes, bekende botanische tuinen en het jaarlijkse Habaneras muziekfestival op het strand.', highlights: ['Jardí Botànic de Cap Roig','Havaneres festival','Camí de Ronda','Vissersboten op strand'], lat: 41.8880, lng: 3.1783 },
  { name: "L'Estartit", slug: 'l-estartit', town: "L'Estartit", region: 'Costa Brava', population: '3200', description: "Kustplaats aan de voet van het Montgrí-massief, poort naar de Medische Eilanden — een van de beste duiklocaties van de Middellandse Zee.", highlights: ['Illes Medes','Duiken','Montgrí kasteel','Strandpromenade'], lat: 42.0505, lng: 3.1870 },
  { name: 'Roses', slug: 'roses', town: 'Roses', region: 'Costa Brava', population: '20000', description: 'Levendige kuststad met een enorme baai, historische citadel en uitstekende gastronomische scene.', highlights: ['Ciutadella de Roses','Playa de Roses','Cap de Norfeu','Castillo de la Trinitat'], lat: 42.2635, lng: 3.1766 },
  { name: "L'Escala", slug: 'l-escala', town: "L'Escala", region: 'Costa Brava', population: '10500', description: "Authentieke kustplaats beroemd om ansjovis, met de Griekse en Romeinse ruïnes van Empúries direct aan zee.", highlights: ['Ruïnes van Empúries','Ansjovisroute','Strand Riells','Oude stad'], lat: 42.1208, lng: 3.1355 },
  { name: 'Sant Feliu de Guíxols', slug: 'sant-feliu-de-guixols', town: 'Sant Feliu de Guíxols', region: 'Costa Brava', population: '22000', description: 'Historische havenstad met een indrukwekkend kloostercomplex, levendig centrum en startpunt van de legendarische kustweg naar Tossa de Mar.', highlights: ['Monestir benedictí','Platja de Sant Feliu','Kustweg naar Tossa','Mercat dominical'], lat: 41.7832, lng: 3.0293 },
  { name: 'Lloret de Mar', slug: 'lloret-de-mar', town: 'Lloret de Mar', region: 'Costa Brava', population: '40000', description: 'De bekendste badplaats van de Costa Brava met prachtige stranden, waterparken en een verrassend mooie oude stad.', highlights: ['Jardins de Santa Clotilde','Castell de Sant Joan','Platja de Lloret','Water World'], lat: 41.7000, lng: 2.8456 },
  { name: 'Blanes', slug: 'blanes', town: 'Blanes', region: 'Costa Brava', population: '39000', description: 'De "poort tot de Costa Brava" met de beroemde botanische tuinen Marimurtra en een gezellige oude vismarkt.', highlights: ['Jardí Botànic Marimurtra','Sa Palomera rots','Vismarkt','Vuurwerkfestival'], lat: 41.6745, lng: 2.7901 },
  { name: 'Figueres', slug: 'figueres', town: 'Figueres', region: 'Alt Empordà', population: '46000', description: 'Geboortestad van Salvador Dalí en thuisbasis van het spectaculaire Dalí Theater-Museum, het meest bezochte museum van Catalonië.', highlights: ['Teatre-Museu Dalí','Kasteel Sant Ferran','La Rambla','Museu del Joguet'], lat: 42.2660, lng: 2.9617 },
  { name: 'Girona', slug: 'girona', town: 'Girona', region: 'Gironès', population: '103000', description: 'Betoverende stad met kleurrijke huizen langs de Onyar, een oud Joods kwartier, gotische kathedraal en Game of Thrones filmlocaties.', highlights: ['Catedral de Girona','Barri Vell','Cases de l\'Onyar','Banys Àrabs','Temps de Flors'], is_featured: true, lat: 41.9794, lng: 2.8214 },
  { name: 'Besalú', slug: 'besalu', town: 'Besalú', region: 'Garrotxa', population: '2400', description: 'Middeleeuws juweel met de iconische Romaanse brug, een van de best bewaarde Joodse badhuizen (mikwe) van Europa.', highlights: ['Pont Romànic','Mikwe (Joods badhuis)','Monestir de Sant Pere','Plaça de la Llibertat'], lat: 42.1991, lng: 2.6987 },
];

const beaches = [
  { name: 'Platja de Sa Riera', slug: 'platja-de-sa-riera', town: 'Begur', region: 'Costa Brava', beach_type: 'zand', length_meters: 200, blue_flag: true, description: 'Prachtig zandstrand omgeven door rotsen en pijnbomen in een beschutte baai bij Begur.', facilities: ['Strandbars','Douches','Strandstoel verhuur','Parkeren'], is_featured: true, lat: 41.9599, lng: 3.2147 },
  { name: 'Cala Aiguablava', slug: 'cala-aiguablava', town: 'Begur', region: 'Costa Brava', beach_type: 'cala', length_meters: 75, blue_flag: false, description: 'Iconische cala met kristalhelder turquoise water, omringd door pijnbomen die tot aan het water reiken.', facilities: ['Duikschool','Kajakverhuur','Restaurant'], is_featured: true, lat: 41.9391, lng: 3.2194 },
  { name: 'Platja de Pals', slug: 'platja-de-pals', town: 'Pals', region: 'Costa Brava', beach_type: 'zand', length_meters: 3500, blue_flag: true, description: 'Uitgestrekt en breed zandstrand met duinen, ideaal voor watersporten en rustige strandwandelingen.', facilities: ['Windsurfen','Kitesurfen','Strandtent','Douches','Parkeren'], is_featured: true, lat: 41.9800, lng: 3.1900 },
  { name: 'Cala Sa Tuna', slug: 'cala-sa-tuna', town: 'Begur', region: 'Costa Brava', beach_type: 'cala', length_meters: 80, blue_flag: false, description: 'Klein, charmant vissersstrandje met oude vissershuisjes gebouwd in de rotsen. Prachtig helder water.', facilities: ['Restaurant','Snorkelen'], lat: 41.9522, lng: 3.2300 },
  { name: 'Platja de Lloret', slug: 'platja-de-lloret', town: 'Lloret de Mar', region: 'Costa Brava', beach_type: 'zand', length_meters: 1630, blue_flag: true, description: 'Het hoofdstrand van Lloret de Mar met grof zand en helder water. Levendig met alle voorzieningen.', facilities: ['Watersporten','Strandbars','Douches','Verhuur ligbedden','Duikschool'], lat: 41.6992, lng: 2.8481 },
  { name: 'Cala del Senyor Ramon', slug: 'cala-del-senyor-ramon', town: 'Santa Cristina d\'Aro', region: 'Costa Brava', beach_type: 'cala', length_meters: 50, blue_flag: false, description: 'Verborgen cala alleen bereikbaar via een bospad, beloond met kristalhelder water en absolute rust.', facilities: ['Snorkelen'], lat: 41.8350, lng: 3.0600 },
  { name: 'Platja Gran de Tossa', slug: 'platja-gran-tossa', town: 'Tossa de Mar', region: 'Costa Brava', beach_type: 'zand', length_meters: 385, blue_flag: true, description: 'Iconisch strand direct onder de middeleeuwse muren van Vila Vella. Pittoresk en goed bereikbaar.', facilities: ['Strandbars','Douches','Verhuur ligbedden','Watersporten'], is_featured: true, lat: 41.7190, lng: 2.9335 },
  { name: 'Platja de Sant Pol', slug: 'platja-de-sant-pol', town: 'Sant Feliu de Guíxols', region: 'Costa Brava', beach_type: 'zand', length_meters: 625, blue_flag: true, description: 'Breed strand gescheiden door een historische boog, uitstekend voor gezinnen met ondiep water.', facilities: ['Strandbars','Douches','Speeltoestellen','Verhuur ligbedden'], lat: 41.7785, lng: 3.0360 },
  { name: 'Cala Estreta', slug: 'cala-estreta', town: 'Palamós', region: 'Costa Brava', beach_type: 'rots', length_meters: 20, blue_flag: false, description: 'Spectaculaire, afgelegen rotsformatie met natuurlijk zwembad. Alleen te bereiken via kustpad (Camí de Ronda).', facilities: ['Snorkelen'], lat: 41.8600, lng: 3.1600 },
  { name: 'Cala Pedrosa', slug: 'cala-pedrosa', town: 'Tamariu', region: 'Costa Brava', beach_type: 'kiezel', length_meters: 40, blue_flag: false, description: 'Afgelegen kiezelstrandje alleen bereikbaar per boot of via lang kustpad. Ongerept en prachtig.', facilities: [], lat: 41.9200, lng: 3.2400 },
  { name: 'Platja de Tamariu', slug: 'platja-de-tamariu', town: 'Tamariu', region: 'Costa Brava', beach_type: 'zand', length_meters: 190, blue_flag: true, description: 'Charmant vissersstrand in de beschutte baai van Tamariu, omgeven door witte huisjes en restaurants.', facilities: ['Restaurants','Douches','Kajakverhuur','Snorkelen'], is_featured: true, lat: 41.9186, lng: 3.2192 },
  { name: 'Platja del Canadell', slug: 'platja-del-canadell', town: 'Calella de Palafrugell', region: 'Costa Brava', beach_type: 'zand', length_meters: 120, blue_flag: false, description: 'Lieflijk strand met vissersbootjes en uitzicht op het eilandje. Startpunt van het Camí de Ronda.', facilities: ['Restaurant','Douches'], lat: 41.8866, lng: 3.1811 },
  { name: 'Platja de Fenals', slug: 'platja-de-fenals', town: 'Lloret de Mar', region: 'Costa Brava', beach_type: 'zand', length_meters: 700, blue_flag: true, description: 'Rustiger alternatief voor het hoofdstrand van Lloret, met goudkleurig zand en helder water.', facilities: ['Strandbars','Douches','Verhuur ligbedden','Speeltuin'], lat: 41.6950, lng: 2.8360 },
  { name: 'Cala Giverola', slug: 'cala-giverola', town: 'Tossa de Mar', region: 'Costa Brava', beach_type: 'kiezel', length_meters: 180, blue_flag: false, description: 'Beschutte kiezelbaai omgeven door hoge kliffen met kristalhelder water, perfect voor snorkelen.', facilities: ['Strandbar','Kajakverhuur','Snorkelen','Parkeren'], lat: 41.7400, lng: 2.8900 },
  { name: 'Platja del Castell', slug: 'platja-del-castell', town: 'Palamós', region: 'Costa Brava', beach_type: 'zand', length_meters: 200, blue_flag: false, description: 'Het laatste onbebouwde strand van de Costa Brava, omgeven door natuur. Absoluut een must-visit.', facilities: ['Geen voorzieningen - puur natuur'], is_featured: true, lat: 41.8690, lng: 3.1450 },
  { name: 'Cala Montgó', slug: 'cala-montgo', town: "L'Escala", region: 'Costa Brava', beach_type: 'zand', length_meters: 350, blue_flag: true, description: "Brede baai met ondiep, rustig water. Populair bij gezinnen en windsurfers. Direct bij L'Escala.", facilities: ['Restaurant','Douches','Windsurfen','Parkeren'], lat: 42.1060, lng: 3.1580 },
  { name: 'Platja de Roses', slug: 'platja-de-roses', town: 'Roses', region: 'Costa Brava', beach_type: 'zand', length_meters: 2200, blue_flag: true, description: 'Kilometerslang strand aan de grote baai van Roses met prachtig uitzicht op de Pyreneeën.', facilities: ['Strandbars','Douches','Watersporten','Verhuur ligbedden','Speeltoestellen'], lat: 42.2635, lng: 3.1800 },
  { name: 'Cala Futadera', slug: 'cala-futadera', town: 'Tossa de Mar', region: 'Costa Brava', beach_type: 'cala', length_meters: 30, blue_flag: false, description: 'Verborgen paradijsje tussen kliffen, alleen bereikbaar via steil pad. Naaktstrand met spectaculair helder water.', facilities: [], lat: 41.7380, lng: 2.8880 },
  { name: 'Cala Pola', slug: 'cala-pola', town: 'Tossa de Mar', region: 'Costa Brava', beach_type: 'cala', length_meters: 50, blue_flag: false, description: 'Kleine, maar schitterende cala omgeven door pijnbomen en rotsen. Bereikbaar via trap vanaf de kustweg.', facilities: ['Strandbar'], lat: 41.7350, lng: 2.8930 },
  { name: 'Platja de Sa Boadella', slug: 'platja-de-sa-boadella', town: 'Lloret de Mar', region: 'Costa Brava', beach_type: 'zand', length_meters: 250, blue_flag: false, description: 'Verborgen strand onder de tuinen van Santa Clotilde, rustiger dan de hoofdstranden van Lloret. Deels naaktstrand.', facilities: ['Strandbar'], lat: 41.6930, lng: 2.8240 },
];

const attractions = [
  { name: 'Teatre-Museu Dalí', slug: 'teatre-museu-dali', town: 'Figueres', region: 'Alt Empordà', category: 'museum', description: 'Het spectaculaire Dalí Theater-Museum, ontworpen door de surrealist zelf, is het meest bezochte museum van Catalonië. Elk detail is een kunstwerk.', price_range: '€€', highlights: ['Mae West kamer','Regenachtige Cadillac','Dalí\'s crypte','Juwelenmuseum'], website: 'https://www.salvador-dali.org', lat: 42.2672, lng: 2.9588, is_featured: true },
  { name: 'Cap de Creus Natuurpark', slug: 'cap-de-creus', town: 'Cadaqués', region: 'Alt Empordà', category: 'natuur', description: 'Het meest oostelijke punt van het Iberisch Schiereiland met bizarre rotsformaties gevormd door de Tramontana wind. Dalí\'s inspiratiebron.', price_range: 'Gratis', highlights: ['Vuurtoren','Bizarre rotsformaties','Zonsopgang','Wandelpaden'], lat: 42.3186, lng: 3.3164, is_featured: true },
  { name: 'Ruïnes van Empúries', slug: 'ruines-van-empuries', town: "L'Escala", region: 'Costa Brava', category: 'historisch', description: "Unieke Grieks-Romeinse opgravingssite direct aan zee. De enige plek in Spanje waar je Griekse en Romeinse steden naast elkaar vindt.", price_range: '€', highlights: ['Griekse stad','Romeins forum','Mozaïeken','Museum','Zeezicht'], website: 'https://www.macempuries.cat', lat: 42.1345, lng: 3.1231, is_featured: true },
  { name: 'Jardí Botànic de Cap Roig', slug: 'jardi-botanic-cap-roig', town: 'Calella de Palafrugell', region: 'Costa Brava', category: 'natuur', description: 'Spectaculaire botanische tuinen op kliffen boven zee met meer dan 1.000 plantensoorten en een jaarlijks muziekfestival.', price_range: '€', highlights: ['Mediterrane planten','Sculpturen','Zeezicht','Cap Roig Festival'], website: 'https://www.caproigfestival.com', lat: 41.8712, lng: 3.1666 },
  { name: 'Castell de Tossa', slug: 'castell-de-tossa', town: 'Tossa de Mar', region: 'Costa Brava', category: 'historisch', description: 'De enige versterkte middeleeuwse stad aan de Catalaanse kust (Vila Vella). Loop over de stadsmuren met adembenemend uitzicht.', price_range: 'Gratis', highlights: ['Stadsmuren','Vuurtoren','Panoramisch uitzicht','Museu Municipal'], lat: 41.7208, lng: 2.9337, is_featured: true },
  { name: 'Vulkanen van La Garrotxa', slug: 'vulkanen-la-garrotxa', town: 'Olot', region: 'La Garrotxa', category: 'natuur', description: 'Natuurpark met 40 inactieve vulkanen en beukenwoods. De Fageda d\'en Jordà is een magisch beukenbos op een lavastroom.', price_range: 'Gratis', highlights: ['Vulcà Croscat','Fageda d\'en Jordà','Santa Margarida krater','Wandelpaden'], lat: 42.1534, lng: 2.4833, is_featured: true },
  { name: 'Catedral de Girona', slug: 'catedral-de-girona', town: 'Girona', region: 'Gironès', category: 'historisch', description: 'Indrukwekkende kathedraal met het breedste gotische schip ter wereld (23m). Filmlocatie uit Game of Thrones.', price_range: '€', highlights: ['Breedste gotische schip','Schepping tapijt','Kloostergang','Game of Thrones'], lat: 41.9876, lng: 2.8260 },
  { name: 'Jardins de Santa Clotilde', slug: 'jardins-santa-clotilde', town: 'Lloret de Mar', region: 'Costa Brava', category: 'natuur', description: 'Elegante neoklassieke tuinen hoog boven zee met Italiaans-geïnspireerde terrassen, fonteinen en sculpturen.', price_range: '€', highlights: ['Zeezicht','Neoklassieke sculpturen','Italiaanse terrassen','Fotogeniek'], lat: 41.6942, lng: 2.8256 },
  { name: 'Museu de la Pesca', slug: 'museu-de-la-pesca', town: 'Palamós', region: 'Costa Brava', category: 'museum', description: 'Interactief museum over de Mediterrane visserijtraditie. Inclusief boottochten met echte vissers en proeverij van Palamós-garnalen.', price_range: '€', highlights: ['Interactief','Boottochten','Garnalen proeverij','Geschiedenis'], website: 'https://www.museudelapesca.org', lat: 41.8476, lng: 3.1281 },
  { name: 'Castell de Púbol', slug: 'castell-de-pubol', town: 'La Pera', region: 'Baix Empordà', category: 'museum', description: 'Het middeleeuwse kasteel dat Dalí aan zijn vrouw Gala schonk. Gevuld met Dalí schilderijen en Gala\'s haute couture collectie.', price_range: '€€', highlights: ['Dalí schilderijen','Gala\'s crypte','Middeleeuwse architectuur','Tuin met olifantssculpturen'], website: 'https://www.salvador-dali.org', lat: 42.0210, lng: 2.9915 },
  { name: 'Pont Romànic de Besalú', slug: 'pont-romanic-besalu', town: 'Besalú', region: 'Garrotxa', category: 'historisch', description: 'De iconische 12e-eeuwse Romaanse brug over de Fluvià, een van de best bewaarde middeleeuwse bruggen van Europa.', price_range: 'Gratis', highlights: ['12e-eeuwse brug','Middeleeuws dorp','Joods badhuis','Fotogeniek'], lat: 42.1991, lng: 2.6987 },
  { name: 'Illes Medes', slug: 'illes-medes', town: "L'Estartit", region: 'Costa Brava', category: 'natuur', description: 'Beschermd marien reservaat met de rijkste onderwaterfauna van de westelijke Middellandse Zee. Paradijs voor duikers.', price_range: '€€', highlights: ['Duiken','Snorkelen','Boottochten','Onderwaterleven','Glasbodemboot'], lat: 42.0472, lng: 3.2235 },
  { name: 'Banys Àrabs de Girona', slug: 'banys-arabs-girona', town: 'Girona', region: 'Gironès', category: 'historisch', description: 'Romaans badhuis uit de 12e eeuw, geïnspireerd op Noordafrikaanse architectuur. Een van de best bewaarde van Europa.', price_range: '€', highlights: ['Romaanse architectuur','Lichtval koepel','Tuin','Nabij kathedraal'], lat: 41.9885, lng: 2.8270 },
  { name: 'GR 92 - Camí de Ronda', slug: 'cami-de-ronda', town: 'Diverse plaatsen', region: 'Costa Brava', category: 'activiteit', description: 'Het legendarische kustpad dat de hele Costa Brava volgt. Oorspronkelijk aangelegd om smokkelaars te bestrijden, nu een van de mooiste wandelroutes van Spanje.', price_range: 'Gratis', highlights: ['Kustpad','Diverse etappes','Verborgen stranden','Panorama\'s'], is_featured: true, lat: 41.8700, lng: 3.1400 },
  { name: 'Aquàrium de Blanes', slug: 'aquarium-blanes', town: 'Blanes', region: 'Costa Brava', category: 'park', description: 'Compact maar informatief aquarium met focus op Mediterrane soorten. Leuk voor gezinnen, gecombineerd met een bezoek aan de botanische tuinen.', price_range: '€', highlights: ['Mediterrane vissen','Interactieve displays','Geschikt voor kinderen'], lat: 41.6700, lng: 2.7900 },
];

const restaurants = [
  { name: 'El Celler de Can Roca', slug: 'el-celler-de-can-roca', town: 'Girona', region: 'Gironès', cuisine_type: 'Catalaans', price_range: '€€€€', michelin_stars: 3, description: 'Driesterren Michelin restaurant van de broers Roca, meermaals verkozen tot beste restaurant ter wereld. Reserveren is maanden van tevoren nodig.', specialties: ['El món','Caramel dessert','Destillaat menu','Wijnpairing'], website: 'https://cellercanroca.com', lat: 41.9930, lng: 2.8050, is_featured: true },
  { name: 'Les Cols', slug: 'les-cols', town: 'Olot', region: 'La Garrotxa', cuisine_type: 'Catalaans', price_range: '€€€', michelin_stars: 2, description: 'Twee Michelin-sterren restaurant in een 15e-eeuwse masia, met focus op vulkanische terroir en lokale producten uit de Garrotxa.', specialties: ['Vulkanische aardappel','Lokale groenten','Seizoensmenu'], website: 'https://www.lescols.com', lat: 42.1760, lng: 2.4890, is_featured: true },
  { name: 'Can Jubany', slug: 'can-jubany', town: 'Calldetenes', region: 'Osona', cuisine_type: 'Catalaans', price_range: '€€€', michelin_stars: 1, description: 'Eén Michelin-ster restaurant van chef Nandu Jubany in een omgebouwde boerderij. Creatieve Catalaanse keuken.', specialties: ['Truffel menu','Catalaans varken','Seizoensgebonden desserts'], website: 'https://www.canjubany.com', lat: 41.9105, lng: 2.4070 },
  { name: 'La Cuina de Can Pipes', slug: 'la-cuina-de-can-pipes', town: 'Begur', region: 'Costa Brava', cuisine_type: 'Mediterraan', price_range: '€€', description: 'Charmant restaurant in het historische centrum van Begur met verse vis en mediterrane keuken in een voormalig winkelpand.', specialties: ['Verse vis','Risotto','Catalaanse tapas','Zelfgemaakte desserts'], lat: 41.9544, lng: 3.2073 },
  { name: 'Restaurant Sa Gambina', slug: 'restaurant-sa-gambina', town: 'Tossa de Mar', region: 'Costa Brava', cuisine_type: 'Vis & Zeevruchten', price_range: '€€', description: 'Visrestaurant direct aan het strand met uitzicht op de middeleeuwse muren. Gespecialiseerd in vers gevangen vis en zeevruchten.', specialties: ['Gamba\'s a la plancha','Paella de mariscos','Suquet de peix','Crema catalana'], lat: 41.7190, lng: 2.9330, is_featured: true },
  { name: 'El Molí de l\'Escala', slug: 'el-moli-de-l-escala', town: "L'Escala", region: 'Costa Brava', cuisine_type: 'Catalaans', price_range: '€€€', description: "Sfeervolle molen uit de 17e eeuw met verfijnde Empordà-keuken. Beroemd om hun ansjovis en rijstgerechten.", specialties: ['Ansjovis van L\'Escala','Arròs negre','Suquet','Crema catalana'], lat: 42.1200, lng: 3.1340 },
  { name: 'Tragamar', slug: 'tragamar', town: 'Calella de Palafrugell', region: 'Costa Brava', cuisine_type: 'Mediterraan', price_range: '€€€', description: 'Stijlvol restaurant op een rotspunt boven zee met de meest spectaculaire zonsondergang van de Costa Brava. Van de groep Tragaluz.', specialties: ['Tartaar','Kreeft','Cocktails','Verse vis'], website: 'https://www.grupotragaluz.com/tragamar', lat: 41.8880, lng: 3.1770, is_featured: true },
  { name: 'Hostal Sa Rascassa', slug: 'hostal-sa-rascassa', town: 'Begur', region: 'Costa Brava', cuisine_type: 'Vis & Zeevruchten', price_range: '€€€', description: 'Legendarisch visrestaurant in het pittoreske haventje van Sa Riera. Al generaties lang in dezelfde familie. Verse vis van het bord.', specialties: ['Gamba\'s van Palamós','Suquet de rap','Bullit de peix','Fideuà'], lat: 41.9600, lng: 3.2150 },
  { name: 'Can Pep', slug: 'can-pep', town: 'Pals', region: 'Costa Brava', cuisine_type: 'Catalaans', price_range: '€€', description: 'Authentiek landrestaurant specialiserend in arròs de Pals (rijst uit Pals) gebakken in houtoven. Een culinaire traditie.', specialties: ['Arròs de Pals','Houtoven gerechten','Catalaanse worst','Crema catalana'], lat: 41.9717, lng: 3.1489, is_featured: true },
  { name: 'Compartir', slug: 'compartir', town: 'Cadaqués', region: 'Costa Brava', cuisine_type: 'Tapas', price_range: '€€€', description: 'Van voormalige elBulli chefs Mateu Casañas, Oriol Castro en Eduard Xatruch. Creatieve tapas om te delen in een betoverende tuin.', specialties: ['Creative tapas','Brioche truffel','Oester met cava','Tuin dining'], website: 'https://www.compartircadaques.com', lat: 42.2887, lng: 3.2766, is_featured: true },
];

const blogPosts = [
  { title: 'De 10 mooiste stranden van de Costa Brava', slug: 'mooiste-stranden-costa-brava', excerpt: 'Van verborgen cala\'s tot uitgestrekte zandstranden — onze selectie van de allermooiste stranden.', content: "De Costa Brava heeft meer dan 200 stranden verspreid over 200 kilometer kustlijn. Van verborgen cala's alleen bereikbaar via kustpaden tot uitgestrekte zandstranden met alle voorzieningen.\n\n## 1. Platja del Castell, Palamós\nHet laatste onbebouwde strand van de Costa Brava. Puur natuur, geen gebouwen, geen strandbar — alleen u en de zee.\n\n## 2. Cala Aiguablava, Begur\nDe iconische turquoise cala die de Costa Brava wereldberoemd maakt. Het water is zo helder dat u vanaf de kliffen de bodem kunt zien.\n\n## 3. Platja de Tamariu\nCharmant vissersstrand omgeven door restaurants en witte huisjes. Perfect voor een dag ontspanning.\n\n## 4. Platja de Pals\n3,5 kilometer breed zandstrand met duinen. Ideaal voor watersporten en lange strandwandelingen.\n\n## 5. Platja Gran de Tossa de Mar\nStrand direct onder de middeleeuwse muren — een uniek decor dat nergens anders te vinden is.", category: 'Reisgids', read_time: '8 min', tags: ['Stranden','Costa Brava','Top 10'], is_featured: true, is_published: true },
  { title: 'Uw caravan winterklaar maken: complete checklist', slug: 'caravan-winterklaar-checklist', excerpt: 'Alles wat u moet doen om uw caravan veilig de winter door te helpen.', content: "Een goede wintervoorbereiding is essentieel voor de levensduur van uw caravan. Volg deze checklist om problemen te voorkomen.\n\n## Waterleidingen\n- Tap al het water af uit leidingen en boiler\n- Gebruik antivries in de afvoeren\n- Laat kranen open staan\n\n## Accu & Elektra\n- Koppel de accu los of gebruik een onderhoudslader\n- Controleer alle zekeringen\n\n## Buitenzijde\n- Was en wax de buitenkant\n- Controleer kitvoegen en repareer waar nodig\n- Smeer alle sloten en scharnieren\n\n## Binnenzijde\n- Maak alles grondig schoon\n- Laat kastjes open voor ventilatie\n- Plaats vochtvreter zakjes\n\n## Stalling\nOverweeg professionele stalling aan de Costa Brava — uw caravan staat klaar wanneer u aankomt!", category: 'Onderhoud', read_time: '6 min', tags: ['Onderhoud','Winter','Checklist'], is_featured: true, is_published: true },
  { title: 'Girona: meer dan een tussenstop', slug: 'girona-stadsgids', excerpt: 'Waarom Girona een volwaardige bestemming is en geen luchthavenstop.', content: "De meeste reizigers kennen Girona alleen van de luchthaven, maar de stad zelf is een verborgen juweel dat minstens twee dagen van uw tijd verdient.\n\n## De kleurrijke huizen van de Onyar\nHet meest iconische beeld van Girona: de pastelkleurige huizen die boven de rivier de Onyar hangen.\n\n## Barri Vell — Het oude centrum\nVerdwaal in de smalle steegjes van het oude Joodse kwartier, een van de best bewaarde van Europa.\n\n## Kathedraal met het breedste schip\nDe kathedraal van Girona heeft het breedste gotische schip ter wereld (23 meter). De trappen ervoor dienden als filmlocatie voor Game of Thrones.\n\n## El Celler de Can Roca\nReserveer maanden vooruit voor het driesterren Michelin restaurant van de broers Roca — meermaals verkozen tot beste restaurant ter wereld.\n\n## Temps de Flors\nBezoek Girona in mei tijdens het bloemenfestival wanneer de hele stad verandert in een bloemententoonstelling.", category: 'Reisgids', read_time: '7 min', tags: ['Girona','Stedentrip','Gastronomie'], is_published: true },
  { title: 'Camí de Ronda: wandelen langs de kust', slug: 'cami-de-ronda-wandelgids', excerpt: 'Het legendarische kustpad van de Costa Brava voor alle niveaus.', content: "Het Camí de Ronda (GR 92) is een oud smokkelpad dat de hele Costa Brava kustlijn volgt. Tegenwoordig is het een van de populairste wandelroutes van Spanje.\n\n## Geschiedenis\nHet pad werd in de 19e eeuw aangelegd zodat de Guardia Civil smokkelaars kon opsporen langs de kust.\n\n## Beste etappes\n**Calella de Palafrugell — Llafranc (40 min)**\nPerfect voor beginners met spectaculair uitzicht.\n\n**Begur — Sa Tuna (1 uur)**\nDoor pijnbomenbossen met verborgen cala's.\n\n**Tossa de Mar — Sant Feliu de Guíxols (4 uur)**\nDe koningin der etappes langs kliffen en verborgen baaien.\n\n## Praktische tips\n- Draag stevige wandelschoenen\n- Neem voldoende water mee\n- Start vroeg in de ochtend (schaduw en koelte)\n- De beste periode is april-juni en september-oktober", category: 'Reisgids', read_time: '6 min', tags: ['Wandelen','Camí de Ronda','Natuur'], is_featured: true, is_published: true },
  { title: 'Salvador Dalí route door de Costa Brava', slug: 'dali-route-costa-brava', excerpt: 'Volg de sporen van de beroemdste surrealisten ter wereld door de Empordà.', content: "Salvador Dalí werd geboren in Figueres en bracht het grootste deel van zijn leven door aan de Costa Brava. Drie musea vormen de 'Dalí-driehoek'.\n\n## Teatre-Museu Dalí, Figueres\nHet hoofdmuseum, ontworpen door Dalí zelf, is het op twee na meest bezochte museum van Spanje. Elk detail is een kunstwerk.\n\n## Casa-Museu Dalí, Portlligat\nHet woonhuis van Dalí aan een beschutte baai bij Cadaqués. Reserveren is verplicht. U ziet zijn atelier, slaapkamer en de tuin precies zoals hij het achterliet.\n\n## Castell Gala Dalí, Púbol\nHet middeleeuwse kasteel dat Dalí schonk aan zijn vrouw Gala. Intiem museum met schilderijen, haar haute couture en Dalí's crypte.", category: 'Reisgids', read_time: '5 min', tags: ['Dalí','Kunst','Cultuur'], is_published: true },
  { title: 'Gastronomische gids: eten aan de Costa Brava', slug: 'gastronomische-gids-costa-brava', excerpt: 'Van Michelin-sterren tot authentieke visrestaurants — de culinaire rijkdom van de regio.', content: "De Costa Brava is een van de gastronomische hotspots van Spanje met meer Michelin-sterren per vierkante kilometer dan bijna elke andere regio.\n\n## Palamós garnalen\nDe beroemdste garnalen van de Middellandse Zee komen uit Palamós.\n\n## Arròs de Pals\nRijst uit de vlakte van Pals, gebakken in traditionele houtovens.\n\n## Ansjovis van L'Escala\nAl eeuwenlang worden ansjovis gezouten en geconserveerd in L'Escala.\n\n## Michelin restaurants\nEl Celler de Can Roca (3★), Les Cols (2★), Compartir en meer maken de regio tot een culinaire bestemming.", category: 'Reisgids', read_time: '7 min', tags: ['Gastronomie','Restaurants','Lokaal eten'], is_featured: true, is_published: true },
  { title: 'Met kinderen naar de Costa Brava', slug: 'costa-brava-met-kinderen', excerpt: 'De beste activiteiten voor gezinnen met kinderen aan de Costa Brava.', content: "De Costa Brava is een fantastische gezinsbestemming met stranden, waterparken, middeleeuwse dorpen en meer.\n\n## Aquaparken\n- **Water World, Lloret de Mar** — Het grootste waterpark van Europa\n- **Aquadiver, Platja d'Aro** — Leuk voor kleinere kinderen\n\n## Kindvriendelijke stranden\n- Platja de Pals (ondiep, breed)\n- Cala Montgó (rustig water)\n- Platja de Sant Pol (speeltoestellen)\n\n## Activiteiten\n- Glasbodemboot naar Illes Medes\n- Kajak langs de kust\n- Middeleeuwse dorpen verkennen (Pals, Peratallada)\n- Butterfly Park, Empuriabrava", category: 'Reisgids', read_time: '5 min', tags: ['Gezin','Kinderen','Activiteiten'], is_published: true },
  { title: 'De beste duikplekken van de Costa Brava', slug: 'duikplekken-costa-brava', excerpt: 'Van de Medes-eilanden tot verborgen grotten — duiken op zijn best.', content: "De Costa Brava biedt enkele van de beste duikmogelijkheden van de Middellandse Zee.\n\n## Illes Medes\nHet marien reservaat bij L'Estartit is de absolute topbestemming. Enorme groepers, murenen, octopussen en spectaculaire onderwatergrotten.\n\n## Carall Bernat\nIconisch duikpunt bij de Medes-eilanden met een 25 meter hoge onderzeese klif.\n\n## Ullastres\nDrie onderwaterbergtoppen voor gevorderde duikers met spectaculaire biodiversiteit.\n\n## Cap de Creus\nWilder en avontuurlijker duiken met sterke stromingen maar unieke rotsvormingen.", category: 'Reisgids', read_time: '5 min', tags: ['Duiken','Watersport','Illes Medes'], is_published: true },
];

export async function POST(request: NextRequest) {
  if (!verifySetupKey(request)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const results = { campings: 0, places: 0, beaches: 0, attractions: 0, restaurants: 0, blog: 0, errors: [] as string[] };

  try {
    // Check if data already exists
    const existingCampings = await getGuideCampings(1, 1);
    if (existingCampings.total > 0) {
      return NextResponse.json({ error: 'Seed data already exists. Delete existing data first.' }, { status: 400 });
    }

    // Seed campings
    for (const c of campings) {
      try { await createGuideCamping(c); results.campings++; } catch (e) { results.errors.push(`Camping ${c.slug}: ${e}`); }
    }

    // Seed places
    for (const p of places) {
      try { await createGuidePlace(p); results.places++; } catch (e) { results.errors.push(`Place ${p.slug}: ${e}`); }
    }

    // Seed beaches
    for (const b of beaches) {
      try { await createGuideBeach(b); results.beaches++; } catch (e) { results.errors.push(`Beach ${b.slug}: ${e}`); }
    }

    // Seed attractions
    for (const a of attractions) {
      try { await createGuideAttraction(a); results.attractions++; } catch (e) { results.errors.push(`Attraction ${a.slug}: ${e}`); }
    }

    // Seed restaurants
    for (const r of restaurants) {
      try { await createGuideRestaurant(r); results.restaurants++; } catch (e) { results.errors.push(`Restaurant ${r.slug}: ${e}`); }
    }

    // Seed blog posts
    for (const bp of blogPosts) {
      try { await createGuideBlogPost(bp); results.blog++; } catch (e) { results.errors.push(`Blog ${bp.slug}: ${e}`); }
    }

    const total = results.campings + results.places + results.beaches + results.attractions + results.restaurants + results.blog;
    return NextResponse.json({ success: true, message: `Seeded ${total} entries`, results });
  } catch (error) {
    console.error('Seed error:', error);
    return NextResponse.json({ error: 'Failed to seed guide data' }, { status: 500 });
  }
}
